### ISSUE TITLE
Sometimes the sun never sets

### ISSUE THREAD

**Issue by matslina** [nathan-osman/go-sunrise#6]
Hey, thanks for this library. Been using it to automatically dim a LED display overnight.

Wanted to mention that stuff breaks a bit for locations and times when/where the sun never sets. E.g.:

    a, b := sunrise.SunriseSunset(69.3321443, -81.6781126, 2020, 6, 15)
    fmt.Println("Igloolik, Canada:", a, b)

Produces `Igloolik, Canada: 292277026596-12-04 15:30:08 +0000 UTC 292277026596-12-04 15:30:08 +0000 UTC`. That looks a bit like `time.Unix(1<<63-1, 0)`. Guessing this isn't intentional?

**Comment by susannahameyer** [comment]
Could we also distinguish between times when the sun doesn't rise vs. not setting to identify periods of continuous darkness or daylight?
